version: '3.8'

services:
  web:
    image: kody06/llamapress:0.1.14
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/llamapress_development
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: >
      bash -c "
        bundle exec rails db:prepare &&
        bundle exec rails server -b 0.0.0.0
      "

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=llamapress_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  bundle_cache: 